# Generated by Django 4.2.1 on 2023-07-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vantablack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_action', models.CharField(max_length=20)),
                ('shared_to_profile', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activity_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vantablack.commentviews')),
                ('activity_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vantablack.postviews')),
                ('activity_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
