# Generated by Django 4.2.1 on 2023-07-09 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vantablack', '0003_alter_activity_history_activity_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentviews',
            name='comment_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postviews',
            name='post_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
