# Generated by Django 4.2.1 on 2023-07-10 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vantablack', '0005_commented_post_activity_liked_comment_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentviews',
            name='comment_likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postviews',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repply_commentviews',
            name='rep_comment_likes',
            field=models.ManyToManyField(blank=True, related_name='rep_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
