# Generated by Django 4.2.1 on 2023-07-23 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vantablack', '0006_alter_commentviews_comment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviews',
            name='post_shares',
            field=models.ManyToManyField(blank=True, related_name='post_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
