# Generated by Django 4.2.1 on 2023-07-23 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vantablack', '0007_postviews_post_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='share_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription_sh', models.TextField(blank=True, max_length=1000000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('share_post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vantablack.postviews')),
                ('share_post_likes', models.ManyToManyField(blank=True, null=True, related_name='share_post_like', to=settings.AUTH_USER_MODEL)),
                ('user_share_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
